In [1]:
#importazione del dataset e esplorazione dei dati

import pandas as pd

data = pd.read_csv("dataset.csv")

data["language"].value_counts()

language
Estonian      1000
Swedish       1000
Thai          1000
Tamil         1000
Dutch         1000
Japanese      1000
Turkish       1000
Latin         1000
Urdu          1000
Indonesian    1000
Portugese     1000
French        1000
Chinese       1000
Korean        1000
Hindi         1000
Spanish       1000
Pushto        1000
Persian       1000
Romanian      1000
Russian       1000
English       1000
Arabic        1000
Italian       1000
Name: count, dtype: int64

In [2]:
data_2 = pd.read_csv("dataset_augmentation.csv",  encoding="ISO-8859-1")
data_2["language"].value_counts()

language
German       1508
English      1462
French       1082
Spanish       851
Portugese     767
Italian       737
Dutch         575
Romanian       48
Swedish        10
Language        8
Label           1
Name: count, dtype: int64

In [3]:
lang = pd.concat([data, data_2], ignore_index=True)
lang["language"].value_counts()

language
English       2462
French        2082
Spanish       1851
Portugese     1767
Italian       1737
Dutch         1575
German        1508
Romanian      1048
Swedish       1010
Estonian      1000
Indonesian    1000
Urdu          1000
Latin         1000
Turkish       1000
Japanese      1000
Tamil         1000
Thai          1000
Chinese       1000
Persian       1000
Pushto        1000
Hindi         1000
Korean        1000
Arabic        1000
Russian       1000
Language         8
Label            1
Name: count, dtype: int64

In [4]:
#Estrazione dei dati necessari per il modello
lang = lang[lang["language"].isin(["English", "Portugese", "French", "Spanish", "Romanian", "Dutch", "Italian", "German"])]

In [5]:
from sklearn.model_selection import train_test_split
#divisione dei dati in dati train e dati test
train_set, test_set = train_test_split(lang, test_size=0.2, stratify=lang["language"], random_state=42)

In [6]:
caratteri_speciali = ['ã', 'â', 'æ', 'è', 'ë', 'î', 'ï', 'œ', 'ù', 'û', 'ÿ',
                     'ñ', 'ă', 'ș', 'ț', 'ö', 'õ', 'å', 'ì', 'ò', 'ß', 'ä',
                      'ã', 'ã', '¿','¡']
len(caratteri_speciali)

26

In [7]:
articoli = [
    " a ", " an ", " the ", "s ", "i ",
    " um ", " uma ", " o ", "a ", " os ", " as ",
    " un ", " une ", " le ", " la ", " les ", " l'", " des ",
     "una", " el ", " los ", " las ", " unos ", " unas ",
    "o ", " unii ", " unele ", " cel ", " cea ", " cei ", " cele ",
    " een ", " de ", " het ", " deze ", " die ",
    " üks ", " teine ", " see ", " need ", " see ",
    " il ", " lo ", " i ", " gli ", " un' ", " uno ",
    " ein ", " eine ", " der ", " die ", " das ", " einige "
]

len(articoli)

53

In [8]:
ngrams = [
    "th", "he", "in", "er", "an", "re", "nd", "at", "on", "not", "op", "ou", "es", 
        "ti", "to", "it", "is", "of", "le", "de", "la", "bij", "et", "se", "un", "or", 
        "te", "nt", "ce", "el", "ech", "em", "na", "di", "so", "ei", "ue", "een", "io", 
        "que", "ra", "me", "su", "va", "ni", "po", "ea", "nh", "ij", "ing", "ar", "sh", 
        "ng", "je", "for", "n't", "ent", "boa ", "bem ", " bem", "are", "how", "how ", "wie"
        "hoe", "j'", "t'", "l'" , "ing" , "ng", "'s", "Não", "ão" , "ça ", "ai", "ch", "gn", "ui"
        "gh", "șa", "ța", "c'", "m'"
]

len(ngrams)

81

In [9]:
saluti = [
    "Hello", "Hi", "Good morning", "Good afternoon", "Good evening", "how are", # English
    "Olá", "Oi", "Bom dia", "Boa tarde", "Boa noite","tudo bem", "como",  # Portuguese
    "Bonjour", "Salut", "Bonsoir", "Coucou", "Allô", "ça va",  # French
    "Hola", "Buenos días", "Buenas tardes", "Buenas noches", "Qué tal", "cómo", "está", # Spanish
    "Bună", "Salut", "Bună dimineața", "Bună ziua", "Bună seara",  # Romanian
    "Hallo", "Hoi", "Goedemorgen", "Goedemiddag", "Goedenavond", "hoe gaat",  # Dutch
    "Ciao", "Buongiorno", "Salve", "Buonasera", "Buonanotte", "come stai",  # Italian
    "Hallo", "Guten Morgen", "Guten Tag", "Guten Abend", "Servus"  # German
]
saluti = list(map(str.lower, saluti))
saluti

['hello',
 'hi',
 'good morning',
 'good afternoon',
 'good evening',
 'how are',
 'olá',
 'oi',
 'bom dia',
 'boa tarde',
 'boa noite',
 'tudo bem',
 'como',
 'bonjour',
 'salut',
 'bonsoir',
 'coucou',
 'allô',
 'ça va',
 'hola',
 'buenos días',
 'buenas tardes',
 'buenas noches',
 'qué tal',
 'cómo',
 'está',
 'bună',
 'salut',
 'bună dimineața',
 'bună ziua',
 'bună seara',
 'hallo',
 'hoi',
 'goedemorgen',
 'goedemiddag',
 'goedenavond',
 'hoe gaat',
 'ciao',
 'buongiorno',
 'salve',
 'buonasera',
 'buonanotte',
 'come stai',
 'hallo',
 'guten morgen',
 'guten tag',
 'guten abend',
 'servus']

In [10]:
pronomi_soggetivi = [
    "i ", "you ", "he ", "she ", "it ", "we ", "they ",
    "eu ", "tu ", "ele ", "ela ", "você ", "nós ", "eles ", "elas ",
    "je ", "tu ", "elle ", "on ", "nous ", "vous ", "ils ", "elles ",
    "yo ", "tú ", "él ", "ella ", "usted", "nosotros", "nosotras", "vosotros", "vosotras", "ellos ", "ellas ", "ustedes ",
    "eu ", "tu ", "el ", "ea ", "noi ", "voi ", "ei ", "ele ",
    "ik ", "jij ", "u ", "hij ", "zij ", "het ", "wij ", "jullie ", "zij ",
    "mina ", "sina ", "tema ", "meie ", "teie ", "nemad ",
    "io ", "tu ", "lui ", "lei ", "esso ", "noi ", "voi ", "loro ",
    "ich ", "du ", "er ", "sie ", "es ", "wir ", "ihr ", "sie "
]

len(pronomi_soggetivi)

74

In [11]:
features = caratteri_speciali + ngrams + saluti + articoli + pronomi_soggetivi
len(features)

282

In [12]:
import string

def transformation(sentences, special_chars):
    res = []
    sentences = list(map(str.lower, sentences))
    for sentence in sentences:
        sent_vector = [0 for _ in range(len(special_chars))]
        for index, char in enumerate(special_chars):
            if char in sentence:
                sent_vector[index] = 1
            else:
                sent_vector[index] = 0
        res.append(sent_vector)
    return res

x_train, y_train = transformation(train_set['Text'], features), train_set['language']

In [13]:
x_test, y_test = transformation(test_set['Text'], features), test_set['language']

In [14]:
#Funzione che valuta il modello.

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def evaluate_model(pred):
    accuracy = accuracy_score(y_test, pred)
    print(f"Accuracy: {accuracy * 100:.2f}%")
    
    print("\nClassification Report:")
    print(classification_report(y_test, pred))
    
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, pred))



In [15]:
from sklearn.naive_bayes import BernoulliNB

naive_bayes = BernoulliNB(alpha=1, fit_prior=True)

naive_bayes.fit(x_train, y_train)

nb_pred = naive_bayes.predict(x_test)
evaluate_model(nb_pred)

Accuracy: 86.46%

Classification Report:
              precision    recall  f1-score   support

       Dutch       0.97      0.84      0.90       315
     English       0.96      0.88      0.92       492
      French       0.94      0.86      0.90       416
      German       0.52      0.98      0.68       302
     Italian       0.88      0.82      0.85       348
   Portugese       1.00      0.82      0.90       353
    Romanian       0.98      0.94      0.96       210
     Spanish       0.95      0.82      0.88       370

    accuracy                           0.86      2806
   macro avg       0.90      0.87      0.87      2806
weighted avg       0.91      0.86      0.87      2806


Confusion Matrix:
[[264   1   3  47   0   0   0   0]
 [  0 434   0  52   5   0   0   1]
 [  1   3 356  47   6   0   0   3]
 [  5   0   0 296   1   0   0   0]
 [  0   2  18  32 284   0   3   9]
 [  1   6   0  38  13 291   0   4]
 [  0   4   0   9   0   0 197   0]
 [  1   4   0  47  14   0   0 304]]


In [16]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB(alpha=1, fit_prior=True)

mnb.fit(x_train, y_train)

pred_m = mnb.predict(x_test)
evaluate_model(pred_m)

Accuracy: 94.83%

Classification Report:
              precision    recall  f1-score   support

       Dutch       0.97      0.96      0.97       315
     English       0.93      0.97      0.95       492
      French       0.94      0.96      0.95       416
      German       0.97      0.96      0.96       302
     Italian       0.91      0.91      0.91       348
   Portugese       0.99      0.93      0.96       353
    Romanian       0.96      0.96      0.96       210
     Spanish       0.94      0.93      0.94       370

    accuracy                           0.95      2806
   macro avg       0.95      0.95      0.95      2806
weighted avg       0.95      0.95      0.95      2806


Confusion Matrix:
[[303   4   3   3   1   0   1   0]
 [  0 477   4   1   6   0   0   4]
 [  2   7 400   0   4   0   0   3]
 [  1   3   0 290   7   1   0   0]
 [  3   5  12   0 317   0   5   6]
 [  1   8   1   1   6 328   2   6]
 [  0   3   3   1   0   0 201   2]
 [  1   7   4   4   8   1   0 345]]


In [17]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()
model_rf.fit(x_train, y_train)

pred_rf = model_rf.predict(x_test)
evaluate_model(pred_rf)

Accuracy: 95.08%

Classification Report:
              precision    recall  f1-score   support

       Dutch       0.96      0.96      0.96       315
     English       0.93      0.96      0.95       492
      French       0.95      0.95      0.95       416
      German       0.97      0.97      0.97       302
     Italian       0.96      0.95      0.96       348
   Portugese       0.99      0.89      0.94       353
    Romanian       0.98      0.97      0.97       210
     Spanish       0.90      0.95      0.93       370

    accuracy                           0.95      2806
   macro avg       0.96      0.95      0.95      2806
weighted avg       0.95      0.95      0.95      2806


Confusion Matrix:
[[302   4   4   2   0   0   2   1]
 [  3 474   7   1   1   0   0   6]
 [  1   9 396   4   1   0   0   5]
 [  2   0   1 294   1   0   0   4]
 [  1   7   1   0 331   1   0   7]
 [  5   7   4   1   6 315   1  14]
 [  1   3   0   0   2   0 203   1]
 [  1   5   4   1   2   3   1 353]]


In [18]:
#Dopo aver sperimentato sugli iperparametri sono arrivato a raggiungere un 97% con il modello SVC e il parametro C che definisce
#la complessita del modello imposto al valore 3.5

from sklearn.svm import SVC

model_svm = SVC(probability=True, C=6)
model_svm.fit(x_train, y_train)

pred_svm = model_svm.predict(x_test)
evaluate_model(pred_svm)

Accuracy: 95.22%

Classification Report:
              precision    recall  f1-score   support

       Dutch       0.97      0.94      0.95       315
     English       0.92      0.97      0.94       492
      French       0.95      0.95      0.95       416
      German       0.97      0.98      0.97       302
     Italian       0.97      0.95      0.96       348
   Portugese       0.98      0.93      0.95       353
    Romanian       1.00      0.96      0.98       210
     Spanish       0.92      0.96      0.94       370

    accuracy                           0.95      2806
   macro avg       0.96      0.95      0.95      2806
weighted avg       0.95      0.95      0.95      2806


Confusion Matrix:
[[297   7   4   3   0   2   1   1]
 [  1 475   4   1   4   2   0   5]
 [  2  13 394   2   1   1   0   3]
 [  1   3   0 295   1   1   0   1]
 [  0   6   3   2 329   0   0   8]
 [  3   4   4   1   3 327   0  11]
 [  1   4   1   0   1   0 201   2]
 [  2   6   4   1   1   2   0 354]]


In [19]:
from sklearn.ensemble import VotingClassifier

ensemble_clf = VotingClassifier(
    estimators=[('nb', mnb), ('rf', model_rf), ('svm', model_svm)],
    voting='soft'  
)

In [20]:
ensemble_clf.fit(x_train, y_train)

pred_ens = ensemble_clf.predict(x_test)

evaluate_model(pred_ens)

Accuracy: 96.01%

Classification Report:
              precision    recall  f1-score   support

       Dutch       0.97      0.95      0.96       315
     English       0.94      0.97      0.96       492
      French       0.95      0.96      0.96       416
      German       0.98      0.99      0.98       302
     Italian       0.97      0.95      0.96       348
   Portugese       0.99      0.93      0.96       353
    Romanian       0.99      0.97      0.98       210
     Spanish       0.92      0.96      0.94       370

    accuracy                           0.96      2806
   macro avg       0.96      0.96      0.96      2806
weighted avg       0.96      0.96      0.96      2806


Confusion Matrix:
[[299   5   7   2   0   0   1   1]
 [  1 478   4   0   4   0   0   5]
 [  2   7 401   1   0   1   0   4]
 [  1   1   0 298   1   0   0   1]
 [  1   4   5   0 331   1   0   6]
 [  3   5   1   1   1 329   1  12]
 [  0   3   1   0   1   0 204   1]
 [  1   5   4   2   2   2   0 354]]


In [21]:
'''from sklearn.ensemble import GradientBoostingClassifier

model_gbc = GradientBoostingClassifier(n_estimators = 70)
model_gbc.fit(x_train, y_train)

pred_gbc = model_gbc.predict(x_test)
evaluate_model(pred_gbc)'''

#Molto lento e non particolarmente migliore di SVC

'from sklearn.ensemble import GradientBoostingClassifier\n\nmodel_gbc = GradientBoostingClassifier(n_estimators = 70)\nmodel_gbc.fit(x_train, y_train)\n\npred_gbc = model_gbc.predict(x_test)\nevaluate_model(pred_gbc)'

In [73]:
import numpy as np

def top_three(classifier, X):
    res = ""
    probabilities = classifier.predict_proba(X)
    labels = classifier.classes_
    dic_languages =[dict(zip(labels, prob)) for prob in probabilities]
    for pred in dic_languages:
        sorted_pred = dict(sorted(pred.items(), key=lambda item: item[1], reverse=True)[:3])
        other = 100
        for key, value in sorted_pred.items():
            sorted_pred[key] = round(value * 100, 2)
            other -= sorted_pred[key]
            res += key + " = " + str(sorted_pred[key]) + '%\n'
        res += "Other = " + str(round(other , 2)) + "%\n"
        
    return res

def finalmodel(sentence):
    if isinstance(sentence, list):
        for phrase in sentence:
            phrase += " "
        sentence = transformation(sentence, features)
    else:
        sentence += " " 
        sentence= transformation([sentence], features)

    for prediction in ensemble_clf.predict(sentence):
        print("the prediction is: " + prediction)

    
    return top_three(ensemble_clf, sentence)

In [74]:
finalmodel([
    "Hello, how are you?",
    "Olá, como você está?",
    "Bonjour, comment ça va?",
    "Hola, ¿cómo estás?",
    "Bună, ce mai faci?",
    "Hallo, hoe gaat het?",
    "Ciao, come stai?",
    "Hallo, wie geht's?"
])

the prediction is: English
the prediction is: Portugese
the prediction is: French
the prediction is: Spanish
the prediction is: Romanian
the prediction is: Dutch
the prediction is: Italian
the prediction is: German


'English = 92.91%\nDutch = 3.85%\nFrench = 1.72%\nOther = 1.52%\nPortugese = 96.76%\nSpanish = 3.18%\nItalian = 0.02%\nOther = 0.04%\nFrench = 97.17%\nPortugese = 2.37%\nEnglish = 0.36%\nOther = 0.1%\nSpanish = 98.13%\nPortugese = 0.81%\nItalian = 0.37%\nOther = 0.69%\nRomanian = 76.46%\nFrench = 11.34%\nItalian = 9.02%\nOther = 3.18%\nDutch = 93.44%\nGerman = 6.28%\nEnglish = 0.2%\nOther = 0.08%\nItalian = 52.56%\nFrench = 31.13%\nRomanian = 6.37%\nOther = 9.94%\nGerman = 68.71%\nEnglish = 16.2%\nDutch = 12.79%\nOther = 2.3%\n'

In [79]:
print(finalmodel("""como estas"""))

the prediction is: Spanish
Spanish = 70.5%
Portugese = 20.35%
German = 6.05%
Other = 3.1%



In [82]:
import joblib


joblib.dump(finalmodel, "language_detection_model.pkl")

['language_detection_model.pkl']